### ISSUE TITLE
 it seems too hard to run the v2, v3, and v4

### ISSUE THREAD

**Issue by yuuch** [petermattis/opttoy#57]
now(2021-11-26) it seems too hard to run the v2, v3, and v4, I can't get the right dependencies version

**Comment by petermattis** [comment]
@yuuch This repo was an experiment that served its purpose 4 years ago of outlining the major structures in a transformation-based optimizer. There is no intention to keep it operational or to do anything further with it. Use if for learning. Fork it and fix the dependencies if you want.
